#ifndef STATIC_INFOEFFECT_H
#define STATIC_INFOEFFECT_H

// 敵に対するダメージ表示
#define INFO_DAMAGENUM_ENEMY			1
#define INFO_DAMAGENUM_ENEMY_LIFETIME	36

// 味方に対するダメージ表示
#define INFO_DAMAGENUM_DOLL				2
#define INFO_DAMAGENUM_DOLL_LIFETIME	30



#endif // STATIC_INFOEFFECT_H