#ifndef STATIC_INFOEFFECT_H
#define STATIC_INFOEFFECT_H

// 敵に対するダメージ表示
#define INFO_DAMAGENUM_ENEMY			1
#define INFO_DAMAGENUM_ENEMY_STRONG		2
#define INFO_DAMAGENUM_ENEMY_RESIST		3
#define INFO_DAMAGENUM_ENEMY_LIFETIME	36

// 味方に対するダメージ表示
#define INFO_DAMAGENUM_DOLL				4
#define INFO_DAMAGENUM_DOLL_STRONG		5
#define INFO_DAMAGENUM_DOLL_RESIST		6
#define INFO_DAMAGENUM_DOLL_LIFETIME	36



#endif // STATIC_INFOEFFECT_H